# sops-nix configuration
# See: https://github.com/Mic92/sops-nix

keys:
  # Host keys - convert SSH host key to age format:
  # ssh-keyscan <hostname> 2>/dev/null | grep ed25519 | ssh-to-age
  #
  # To get larkbox's key:
  # ssh-keyscan larkbox.local 2>/dev/null | grep ed25519 | ssh-to-age
  - &larkbox age1pgyawfqrlvzwks4y2dq2u486lyz47qwu3uyt5ftazn3at70pxs0q9xwj6u

  # Personal key for editing secrets (not for host decryption)
  - &personal age188usuuflnprxceyxxa4c79hgajgyzjzsuwrlpn0rntdfm4ujsv2swfx743

  # Add more hosts here as needed:
  # - &newhost age1yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy

creation_rules:
  # Larkbox-specific secrets
  - path_regex: secrets/larkbox\.yaml$
    key_groups:
      - age:
          - *larkbox
          - *personal

  # Shared secrets (all hosts can decrypt)
  # Add more host keys here when you have multiple hosts
  - path_regex: secrets/shared\.yaml$
    key_groups:
      - age:
          - *larkbox
          - *personal
          # - *newhost
